version: "3"
services:
  node-dev:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=18.17.0
        - LOCAL_WORKDIR=/app
    tty: true
  rust-dev:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.rust
      args:
        - RUST_VERSION=1.71.0
        - LOCAL_WORKDIR=/app
    tty: true

  ts-fastify-api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=18.17.0
        - LOCAL_WORKDIR=${PWD}
    volumes:
      - .:/${PWD}
      - node_modules:/${PWD}/node_modules
    command: pnpm --filter "@my-org/ts-fastify-api" dev
    ports:
      - 33000:3000 # api
      - 9229:9229 # app debug
      - 9230:9230 # test debug
    env_file:
      - ./services/ts-fastify-api/.env

  rust-axum-api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.rust
      args:
        - RUST_VERSION=1.71.0
    volumes:
      - .:/app
      - cargo_target:/app/target
    command: cargo watch -x 'run -p rust-axum-api'
    ports:
      - 33001:3000

volumes:
  node_modules:
  cargo_target:
