version: "3"
services:
  node-dev:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=18.17.0
        - APP_WORKDIR=/app
      tags:
        - "s2l-node"
    tty: true

  ts-fastify-api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=18.17.0
        - LOCAL_WORKDIR=${PWD}
    command: pnpm --filter "@s2lsoftener/ts-fastify-api" dev
    env_file:
      - ./services/ts-fastify-api/.env
    volumes:
      - .:/${PWD}
      - node_modules:/${PWD}/node_modules
    ports:
      - 33000:3000 # api
      - 9229:9229 # api debug
      - 9230:9230 # test debug

  ts-random-word-api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.node
      args:
        - NODE_VERSION=18.17.0
        - LOCAL_WORKDIR=${PWD}
    command: pnpm --filter "@s2lsoftener/ts-random-word-api" dev
    env_file:
      - ./services/ts-random-word-api/.env
    volumes:
      - .:/${PWD}
      - node_modules:/${PWD}/node_modules
    ports:
      - 33002:3000 # api
      - 9231:9229 # api debug
      - 9232:9230 # test debug

  rust-axum-api:
    build:
      context: .
      dockerfile: ./dev/Dockerfile.rust
      args:
        - RUST_VERSION=1.71.0
    volumes:
      - .:/app
      - cargo_target:/app/target
    command: cargo watch -x 'run -p rust-axum-api'
    ports:
      - 33001:3000

volumes:
  node_modules:
  cargo_target:
