version: "3"
services:
  ts-fastify-api:
    build:
      args:
        - LOCAL_WORKDIR=${PWD}
    volumes:
      - .:/${PWD}
      - node_modules:/${PWD}/node_modules
    ports:
      - 33000:3000 # api
      - 9229:9229 # app debug
      - 9230:9230 # test debug
