ARG RUST_VERSION="1.71.0"
FROM lukemathwalker/cargo-chef:latest-rust-${RUST_VERSION} AS chef

RUN cargo install cargo-watch
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json
COPY . .
