name: Test PR

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  js-build:
    name: (JS) Install deps & Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm -r exec tsc
      - uses: actions/cache/save@v3
        with:
          path: |
            packages/*/dist
            services/*/dist
          key: tsc-${{ github.run_id }}-${{ github.run_attempt }}

  js-unit-test:
    name: (JS) Unit Tests
    runs-on: ubuntu-latest
    needs: js-build
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - uses: actions/cache/restore@v3
        with:
          path: |
            packages/*/dist
            services/*/dist
          key: tsc-${{ github.run_id }}-${{ github.run_attempt }}
      - run: pnpm run -r unit-test

  js-lint:
    name: (JS) Format & Lint
    runs-on: ubuntu-latest
    needs: js-build
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - uses: actions/cache/restore@v3
        with:
          path: |
            packages/*/dist
            services/*/dist
          key: tsc-${{ github.run_id }}-${{ github.run_attempt }}
      - run: pnpm -r exec prettier ./src --check
      - run: pnpm -r exec eslint ./src

  js-docker-build:
    name: (JS) Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      # https://docs.docker.com/build/ci/github-actions/cache/#local-cache
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dev/Dockerfile.node
          tags: s2l-node:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            NODE_VERSION=18.17.0
            LOCAL_WORKDIR=/app
      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  js-integration-test:
    name: (JS) Integration Tests!
    runs-on: ubuntu-latest
    needs: js-docker-build
    strategy:
      matrix:
        package: [ts-fastify-api]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dev/Dockerfile.node
          tags: s2l-node:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            NODE_VERSION=18.17.0
            LOCAL_WORKDIR=/app
          load: true
      - run: ./dev/init-env.sh
      - run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm ${{ matrix.package }} /bin/bash -c "pnpm --filter @my-org/${{ matrix.package }} int-test"
