name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  # include a step to redo tests
  publish:
    name: Publish to GitHub Packages Registry
    runs-on: ubuntu-latest
    outputs:
      published: steps.changesets.outputs.published
      publishedPackages: steps.changesets.outputs.publishedPackages
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          cache: pnpm
      - run: pnpm install
      - run: pnpm -r exec tsc
      - name: Create Release PR or Publish+Deploy
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  echo:
    name: Echo
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - env:
          PUBLISHED: ${{ needs.publish.outputs.published }}
          PUBLISHED_PACKAGES: ${{ needs.publish.outputs.publishedPackages }}
        run: echo $PUBLISHED $PUBLISHED_PACKAGES

  deploy-develop:
    name: Deploy to Develop
    needs: publish
    if: needs.publish.outputs.published == 'true'
    runs-on: ubuntu-latest
    steps:
      - run: echo Pretend to publish to develop ${{ needs.publish.outputs.publishedPackages }}

  deploy-production:
    name: Deploy to Production
    needs: [publish, deploy-develop]
    runs-on: ubuntu-latest
    steps:
      - run: echo Pretend to publish to production ${{ needs.publish.outputs.publishedPackages }}
